In [3]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
# Exercici 1: Carregar “data” i "target" del conjunt de dades, 
# i visualitza els 10 primers registres de cadascun


from sklearn.datasets import load_iris

iris = load_iris()


datos = iris.data[:10]

print("Los 10 primeros registros de 'data' son: ")
print(datos)

clase = iris.target[:10]

print("Los 10 primeros registros de 'target' son:", clase)

Los 10 primeros registros de 'data' son: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Los 10 primeros registros de 'target' son: [0 0 0 0 0 0 0 0 0 0]


In [5]:
# Exercici 2: Concatena data i target en un nou array. Mostra 5 primers registres

import numpy as np


from sklearn.datasets import load_iris

iris = load_iris()

datos = iris.data

clase = iris.target

array_conjunto = np.hstack((datos,clase.reshape(-1,1)))

print(array_conjunto[:5])



[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [6]:
# Exercici 3: Calcula mitjana i desviació estàndard de sepal length i petal length (cm)
# Mostrar resultat amb 2 decimals


import numpy as np


from sklearn.datasets import load_iris

iris = load_iris()

datos = iris.data

columna_sl = 0

sepal_length = [sepal_le[columna_sl] for sepal_le in datos] 

a = round(np.mean(sepal_length),2)

print("La media de 'sepal length' es", a)

desv = round(np.std(sepal_length),2)

print("La desviación estándar de 'sepal length' es:", desv)

columna_pl = 2

petal_length = [petal_le[columna_pl] for petal_le in datos]

b = round(np.mean(petal_length),2)

print("La media de 'petal length' es:", b)

desv1 = round(np.std(petal_length),2)

print("La desviación estándar de 'petal length' es:", desv1)



La media de 'sepal length' es 5.84
La desviación estándar de 'sepal length' es: 0.83
La media de 'petal length' es: 3.76
La desviación estándar de 'petal length' es: 1.76


In [7]:
# Exercici 4: Selecciona una mostra aleatòria de 20 registres del conjunt que has 
# obtingut en l´exercici anterior.


array_conjunto = np.hstack((datos,clase.reshape(-1,1)))

muestra_random = np.random.randint(150,size=20)

array_conjunto[muestra_random,:]


array([[5.8, 4. , 1.2, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [7.3, 2.9, 6.3, 1.8, 2. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [4.9, 3.1, 1.5, 0.2, 0. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [5.5, 2.4, 3.7, 1. , 1. ]])

In [8]:
# Exercici 5: La mitjana i desv. estàndard de cada característica per espècie.

import numpy as np

from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target

arr = np.hstack((x, y.reshape(-1, 1)))

clases = np.unique(y)

medias_por_clase = []
desv_por_clase = []

for clase in clases:
    
    datos_clase = arr[y == clase][:, :-1] 
    media_clase = np.mean(datos_clase, axis=0)
    medias_por_clase.append(media_clase)
    
    desviacion_estandar_clase = np.std(datos_clase, axis=0)
    desv_por_clase.append(desviacion_estandar_clase)

matriz_medias = np.array(medias_por_clase)

print("Matriz de medias por clase:")
print(matriz_medias)

matriz_desviaciones_estandar = np.array(desv_por_clase)

print("Matriz de Desviaciones Estándar por Clase:")
print(matriz_desviaciones_estandar)

Matriz de medias por clase:
[[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]
Matriz de Desviaciones Estándar por Clase:
[[0.34894699 0.37525458 0.17191859 0.10432641]
 [0.51098337 0.31064449 0.46518813 0.19576517]
 [0.62948868 0.31925538 0.54634787 0.27188968]]


In [9]:
# Exercici 6: Calcula la quantitat de mostres per espècie

import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
clase = iris.target
datos = iris.data

especie, muestras = np.unique(clase, return_counts=True)


# creamos diccionario con zip de las 2 listas que nos interesan(target names y nº muestras)

counts_especies = dict(zip(iris.target_names, muestras))

print("La cantidad de muestras por especie es:")
print(counts_especies)


#  Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

#  numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)

sepal_length = datos[:, 0]

medias_sepal = [np.mean(sepal_length[clase == clase1])for clase1 in range(3)]


print(medias_sepal)

max_media_sepal_length = np.argmax(medias_sepal)

nombres_especies = ["setosa", "versicolor", "virginica"]

especie_max_media = nombres_especies[max_media_sepal_length]

print("La especie con el valor máximo medio de sepal length es: " ,especie_max_media)


La cantidad de muestras por especie es:
{'setosa': 50, 'versicolor': 50, 'virginica': 50}
[5.006, 5.936, 6.587999999999998]
La especie con el valor máximo medio de sepal length es:  virginica


In [10]:
# Exercici 7:  Calcula la matriu de correlació entre les variables.

import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
datos = iris.data
clase = iris.target



#matriz_correlacion = np.corrcoef(x, rowvar=False) utilizo iris.data

matriz_correlacion = np.corrcoef(datos,rowvar=False)

# rowvar=false para que coja el valor de las columnas que son las variables, no las filas


print("La matriz de correlación es: ")
print(matriz_correlacion)



# Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho

petal_length = array_conjunto[:, 2]


media_petal_length = round(np.mean(petal_length, axis=0),2)

print("Media petal length: ", media_petal_length)

valores_mayores_media = petal_length[petal_length > media_petal_length]

print("Los valores mayores a la media de petal length son: ")

print(valores_mayores_media)

# Troba la mostra amb els pètals més grans.

petalo_mas_grande = np.argmax(petal_length)
print("La muestra con los pétalos más grandes es la número: ",petalo_mas_grande)
muestra_petalo_mas_grande = array_conjunto[petalo_mas_grande]
print(muestra_petalo_mas_grande)

La matriz de correlación es: 
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
Media petal length:  3.76
Los valores mayores a la media de petal length son: 
[4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]
La muestra con los pétalos más grandes es la número:  118
[7.7 2.6 6.9 2.3 2. ]


In [11]:
# Exercici 8: Troba l'espècie amb la diferència més gran entre 
# la longitud mitjana de sèpals i pètals

import numpy as np


# diferencia promedio entre longitud de sépalos y longitud de pétalos por especie
diferencias_promedio = []
for etiqueta in range(3):
    sepalos_por_especie = array_conjunto[(clase == etiqueta)][:, 0]  # Longitud de los sépalos para esta especie
    petalos_por_especie = array_conjunto[(clase == etiqueta)][:, 2]  # Longitud de los pétalos para esta especie
    diferencia_media = np.mean(sepalos_por_especie) - np.mean(petalos_por_especie)
    diferencias_promedio.append(diferencia_media)

# clase con la mayor diferencia promedio
etiqueta_max_diferencia = np.argmax(diferencias_promedio)
print("Etiqueta especie con diferencia promedio más alta: ", etiqueta_max_diferencia)


nombres_especies = ["setosa", "versicolor", "virginica"]
especie_max_diferencia = nombres_especies[etiqueta_max_diferencia]


print("Especie con mayor diferencia entre media de longitud sépalo y pétalo: ", especie_max_diferencia)


Etiqueta especie con diferencia promedio más alta:  0
Especie con mayor diferencia entre media de longitud sépalo y pétalo:  setosa
